## Installing Numpy

In [76]:
#pip install numpy

In [77]:
import numpy

In [ ]:
numpy.__version__

In [78]:
numpy.array ( [1,5,7,9])

array([1, 5, 7, 9])

## 1D Numpy Array Part-1

In [80]:
import numpy as np

In [7]:
np.array ( [ 8,2,12,10])

array([ 8,  2, 12, 10])

In [9]:
np.array ( [ 1,5,7,9,4,5,8,93,0])

array([ 1,  5,  7,  9,  4,  5,  8, 93,  0])

## 2D Numpy Array [Part 2]

In [12]:
np.array( [2,18,19])

array([ 2, 18, 19])

In [13]:
np.array ( [8,19,13])

array([ 8, 19, 13])

In [14]:
np.array ( [ [2,18,19] , [8,19,13] ])

array([[ 2, 18, 19],
       [ 8, 19, 13]])

In [16]:
np.array( [ [8,2,12,10,99,10] ,[7,12,44,31,97,22] , [2,18,19,58,9,85] ,[8,19,13,79,7,17] ])

array([[ 8,  2, 12, 10, 99, 10],
       [ 7, 12, 44, 31, 97, 22],
       [ 2, 18, 19, 58,  9, 85],
       [ 8, 19, 13, 79,  7, 17]])

copy below 1D numpy arrays to create two dimentional arrays

In [ ]:
 # [8,2,12,10,99,10],[7,12,44,31,97,22] ,[2,18,19,58,9,85],[8,19,13,79,7,17] 

## 3D Numpy Array [Part 3]

In [ ]:
np.array (  [ [[ 2,18,19], [8,19,13]] , [[ 88,11,55], [99,66,77]] ]  )

In [ ]:
np.array( [ [[ 1,7,0],[0,6,9]] , [[ 88,11,55],[99,66,77]] , [[ 2,5,8],[15,12,10]] ])

Copy below arrays to create the above 3 D arrays

In [ ]:
np.array (  [[ 2,18,19], [8,19,13]] )

In [ ]:
np.array (  [[ 88,11,55], [99,66,77]] )

In [ ]:
np.array ( [[ 1,7,0],[0,6,9]])

In [ ]:
np.array ( [[ 88,11,55],[99,66,77]])

In [ ]:
np.array ( [[ 2,5,8],[15,12,10]]  )

## Arange Function [Part -4 ]

In [3]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
np.arange(15,24)

array([15, 16, 17, 18, 19, 20, 21, 22, 23])

In [5]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

In [7]:
np.arange(1,35,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [8]:
np.arange(1,35,5,dtype=float)

array([ 1.,  6., 11., 16., 21., 26., 31.])

In [9]:
np.arange(1,10,2.0)

array([1., 3., 5., 7., 9.])

## Reshape & Resize [Part 5]

In [10]:
x= np.arange(0,18)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

#### Resize

In [11]:
x.resize(6,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [13]:
x.resize ( 3,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

#### 2D TO 3D

In [15]:
x.resize( 3,2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

#### 1D TO 3D

In [16]:
x= np.arange(0,18)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [24]:
x.resize ( 3,2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

### Reshape

In resize original array gets upated into the new shape
But in resahpe original array remains unchanged

In [17]:
x= np.arange(0,18)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [18]:
x.resize ( 3,2,3)

In [19]:
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [20]:
y= np.arange(0,18)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [21]:
y.reshape ( 3,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [22]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

## Indexing 1D [Part -06]

In [23]:
import numpy as np

In [24]:
x=np.array( [ 8,2,12,10])
x

array([ 8,  2, 12, 10])

In [ ]:
x[1]

In [ ]:
x[3]

#### Reverse Indexing

In [ ]:
import numpy as np

In [ ]:
np.array( [ 8,2,12,10])

In [ ]:
x[-3]

In [ ]:
x[-2]

##  Indexing 2D [Part -07]

In [28]:
x = np.array([[2,18,19],[8,19,13]])
x

array([[ 2, 18, 19],
       [ 8, 19, 13]])

In [29]:
x[1 , 2]

13

In [30]:
x[1 , 1]

19

In [31]:
y=np.arange(25)
y.resize(5,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
y[2 , 2]

12

In [34]:
y[4 ,4 ]

24

In [35]:
y [-1,-1]

24

##  Indexing 3D [Part -08]

In [ ]:
import numpy as np

In [36]:
x= np.arange(27)
x.resize(3,3,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [37]:
x = np.array ( [[[2,21,11],[6,8,7],[1,11,12]] , [[4,9,4],[0,0,5],[0,0,1]],[[14,27,8],[0,0,51],[0,0,44]]] )
x

array([[[ 2, 21, 11],
        [ 6,  8,  7],
        [ 1, 11, 12]],

       [[ 4,  9,  4],
        [ 0,  0,  5],
        [ 0,  0,  1]],

       [[14, 27,  8],
        [ 0,  0, 51],
        [ 0,  0, 44]]])

In [ ]:
x[0]

In [ ]:
x[0,2]

In [38]:
x[0,2,1]

11

In [ ]:
x[1,0 ,1]

In [ ]:
x[0 ,1, 1]

In [ ]:
x[0,2 ,1]

## Slicing 1D [Part-9]

In [ ]:
import numpy as np

In [39]:
x = np.arange(8,19,2)
x

array([ 8, 10, 12, 14, 16, 18])

In [40]:
x[1 :4]

array([10, 12, 14])

In [41]:
x[0: 4]

array([ 8, 10, 12, 14])

In [42]:
x[0 : 3]

array([ 8, 10, 12])

#### Slicing using reverse indexing

In [43]:
x[-6 : -2]

array([ 8, 10, 12, 14])

In [44]:
x [ -5 : -1]

array([10, 12, 14, 16])

## 2D slicing [Part 10]

In [ ]:
import numpy as np

In [45]:
x = np.arange(0,32,2)
x.resize(4,4)
x

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [46]:
x[0:2]

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [47]:
x[0:2 ,0:2]

array([[ 0,  2],
       [ 8, 10]])

In [48]:
x[0:2]

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [49]:
x[0:2 , 0: 3]

array([[ 0,  2,  4],
       [ 8, 10, 12]])

## 3D slicing [Part 11]

In [50]:
import numpy as np

In [53]:
x = np.arange(2,56,2)
x.resize(3,3,3)
x

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]],

       [[38, 40, 42],
        [44, 46, 48],
        [50, 52, 54]]])

In [54]:
x[0:2]

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]]])

In [55]:
x[0:2 , 0:2]

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[20, 22, 24],
        [26, 28, 30]]])

In [56]:
x[0:2 , 0:2 ,0:2]

array([[[ 2,  4],
        [ 8, 10]],

       [[20, 22],
        [26, 28]]])

In [57]:
x[0:3 ,0:2 ,0:2]

array([[[ 2,  4],
        [ 8, 10]],

       [[20, 22],
        [26, 28]],

       [[38, 40],
        [44, 46]]])

## Updating Arrays [Part 12]

#### Replace single element by indexing

In [58]:
x =  np.arange(0,32,2)
x.resize(4,4)
x

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [59]:
x [1,1] = 100

In [60]:
x[1,2] = 1255

#### Replace multiple elements by Slicing

In [ ]:
x

In [ ]:
x[0:2, 0:2] = 222

In [ ]:
x[1:3 ,1:3] =589

#### Replace All Elements

In [ ]:
x [:] = 12289

####  Replacing the diagonal values only

In [ ]:
x=np.arange(0,32,2)
x.resize(4,4)
x

In [ ]:
np.fill_diagonal(x,15)
x

In [ ]:
np.fill_diagonal(x,[10,20,30,40])
x

In [ ]:
np.fill_diagonal(x,[1,3])
x

#### Replacing with Conditions

In [ ]:
x < 4

In [ ]:
x [ x < 4] = 1000

In [ ]:
x

In [ ]:
x == 1000

In [ ]:
x [x == 1000] = 11

In [ ]:
x

In [ ]:
x[x<4] = 222
x

## Creating Arrays with Different Methods [Part-13]

In [61]:
np.arange ( 0 , 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(15,35)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34])

In [63]:
np.arange(15,35 ,2)

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [64]:
np.arange( 15,35 ,3,dtype =float)

array([15., 18., 21., 24., 27., 30., 33.])

In [65]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
np.arange(0,15,2.0)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [67]:
np.arange(0,18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

#### Reshape and Resize

In [ ]:
x = np.arange(0,18)
x

In [ ]:
x.reshape(3,6)

In [ ]:
x

In [ ]:
x.resize(3,6)

In [ ]:
x

In [ ]:
x.reshape(6,3)

In [ ]:
x.reshape(3,3,2)

##### Random

In [ ]:
x = np.random.randint(0,100,(3,10))
x

In [ ]:
x = np.random.randint(0,10,(5,3))
x

In [ ]:
x = np.random.uniform(0,10,(4,3))
x

##### Linspace

In [ ]:
np.linspace( 0, 15, 4)  

In [ ]:
np.linspace(0, 10 ,3)

In [ ]:
np.linspace( 0, 5, 20 )  

##### Zeros

In [ ]:
np.zeros(shape = (3,10) )

##### Ones

In [ ]:
p=np.ones( shape=(2,3), dtype=np.int16 )                # depth/layers=2,rows=3,columns=4 ,dtype can also be specified
p

##### Eye

In [ ]:
np.eye(3)

##### Diag

In [ ]:
y = np.array([4,5,10])
y

In [ ]:
np.diag(y)

In [ ]:
y=np.array([4,5,6,10,20])
y

In [ ]:
np.diag(y)

##### Empty

In [ ]:
np.empty( (2,3) ) 

##### Repeat

In [ ]:
np.repeat([1,2,3,5,6],5)

## Basic Math Operations [Part-14]

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(0,10,(2,2))
b = np.random.randint(0,10,(2,2))

In [ ]:
a

In [ ]:
b

In [ ]:
a-b

In [ ]:
a+b

In [ ]:
a*b

In [ ]:
a/b

In [ ]:
b/a

In [ ]:
a*b

In [ ]:
np.dot( a ,b)

In [ ]:
a**2

In [ ]:
np.sqrt(a) #square root

In [ ]:
np.cbrt(a) #cuberoot

In [ ]:
np.exp(a) 

## Aggregate Functions [Part-15]

In [ ]:
import numpy as np

In [69]:
a = np.arange(1,7)
a.resize(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.sum(a)

In [ ]:
np.sum( a , axis =0)

In [ ]:
np.sum( a ,axis =1)

In [ ]:
np.prod(a)

In [ ]:
np.prod(a,axis = 1)

In [ ]:
np.prod(a,axis =0)

In [ ]:
np.max(a)

In [70]:
np.average(a )

3.5

In [71]:
np.average(a ,axis= 1)

array([2., 5.])

In [72]:
np.average(a ,axis= 0)

array([2.5, 3.5, 4.5])

In [75]:
np.min(a )

1

In [73]:
np.min(a ,axis =1)

array([1, 4])

In [74]:
np.min(a ,axis =0)

array([1, 2, 3])

In [ ]:
np.median(a)

#### Aggregate Functions with Multiple arrays

In [ ]:
a = np.arange(1,7)
a.resize(2,3)
a

In [ ]:
b = np.random.randint(0,10,(2,3))
c = np.random.randint(0,10,(2,3))

In [ ]:
a

In [ ]:
b

In [ ]:
c

In [ ]:
np.maximum(a,b,c)

In [ ]:
np.maximum(a,b)

In [ ]:
np.minimum(a,b)

#### Other aggregate functions to explore

In [ ]:
np.corrcoef(a)
np.argmax(a)
np.percentile(a, 50)
np.cumprod(a,0)  
np.cumsum(a)
np.std(a)
np.var(a)

## Join [Part-16]

In [ ]:
import numpy as np

In [ ]:
a1= np.arange(9)
a1

In [ ]:
b1= np.arange(10,19)
b1

In [ ]:
a2= np.arange(9)
a2.resize(3,3)
a2

In [ ]:
b2= np.arange(10,19)
b2.resize(3,3)
b2

In [ ]:
a1

In [ ]:
b1

##### By concantinate function

In [ ]:
np.concatenate( (a1,b1 ) )

In [ ]:
a2

In [ ]:
b2

In [ ]:
np.concatenate( (a2,b2 ) )

In [ ]:
np.concatenate( (a2,b2 ), axis =1 )

##### By Stack function

In [ ]:
a1

In [ ]:
b1

In [ ]:
np.vstack( ( a1,b1, a1) )

In [ ]:
np.hstack( (a1,b1))

In [ ]:
a2

In [ ]:
b2

In [ ]:
np.vstack( ( a2,b2) )

In [ ]:
a1

In [ ]:
a2

In [ ]:
np.concatenate( (a1,a2 ) )

In [ ]:
np.vstack( ( a1,a2) )

##### Append

In [ ]:
b2

In [ ]:
a1

In [ ]:
np.append(b2,a1)

## 1D Array Spliting [Part-17]

In [ ]:
import numpy as np 

In [ ]:
x=np.arange(1,19)
x

In [ ]:
np.split(x ,2 )

In [ ]:
np.split(x ,3 )

#####  Custom Split

In [ ]:
x

In [ ]:
np.split ( x , [4 ,6,10,13])

In [ ]:
x=np.arange(1,19,3)
x

In [ ]:
np.split ( x , [3,5])

##### Accessing Splited Arrays

In [ ]:
x=np.arange(1,19)
x

In [ ]:
np.split(x ,3)

In [ ]:
np.split(x ,3)[1]

In [ ]:
np.split(x ,3)[2]

In [ ]:
np.split( x ,3)[-1]

##### Unequal Spliting

In [ ]:
x=np.arange(1,11)
x

In [ ]:
np.split(x, 3)

In [ ]:
np.array_split(x,3)

In [ ]:
x=np.arange(1,12)
x

In [ ]:
np.array_split( x ,3)

## 2D Array Spliting [Part-18]

In [ ]:
Image(filename='Np_image/2d_array_split_0.jpg') 

In [ ]:
import numpy as np

In [ ]:
x=np.arange(1,17).reshape(4,4)
x

In [ ]:
np.split(x , 2 ) 

In [ ]:
np.split(x , 4 ) 

In [ ]:
x

In [ ]:
np.split(x , 2 ,axis=1)

In [ ]:
x=np.arange(1,17).reshape(8,2)
x

In [ ]:
np.split( x, [2,5,7])


## 3D Array Spliting [Part-19]

In [51]:
import numpy as np

In [52]:
x =  np.arange(1,49).reshape(4,3,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [54]:
np.split( x , 2)

[array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]),
 array([[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]],
 
        [[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]])]

In [55]:
np.split( x , 4)

[array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]),
 array([[[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]),
 array([[[25, 26, 27, 28],
         [29, 30, 31, 32],
         [33, 34, 35, 36]]]),
 array([[[37, 38, 39, 40],
         [41, 42, 43, 44],
         [45, 46, 47, 48]]])]

##### Depth Split

In [56]:
x=np.arange(1,33).reshape(2,4,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [58]:
np.dsplit ( x , 2)

[array([[[ 1,  2],
         [ 5,  6],
         [ 9, 10],
         [13, 14]],
 
        [[17, 18],
         [21, 22],
         [25, 26],
         [29, 30]]]),
 array([[[ 3,  4],
         [ 7,  8],
         [11, 12],
         [15, 16]],
 
        [[19, 20],
         [23, 24],
         [27, 28],
         [31, 32]]])]

##### Depth split in Row wise

In [61]:
x=np.arange(1,33).reshape(2,4,4)
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]]])

In [62]:
 np.hsplit(x,2) 

[array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24]]]),
 array([[[ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[25, 26, 27, 28],
         [29, 30, 31, 32]]])]

In [63]:
np.vsplit(x,2) #this is same as split in 3d ie split wrt layers

[array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]]),
 array([[[17, 18, 19, 20],
         [21, 22, 23, 24],
         [25, 26, 27, 28],
         [29, 30, 31, 32]]])]

## Iterations [Part-20]

In [ ]:
import numpy as np

In [ ]:
x= np.arange(0,5)
x

In [ ]:
for i in x:
    print(i)

#### 2D Iterations

In [ ]:
x= np.arange(0,12).reshape(4,3)
x

In [3]:
from IPython.display import Image
import numpy as np

In [ ]:
for i in x :
    print(i)

In [ ]:
x= np.arange(0,12).reshape(3,4)
x

In [ ]:
for i in x:
    print(i)

In [ ]:
for i in x:
    for j in i:
        print(j)

In [ ]:
for i in np.nditer(x):
    print(i)

#### 3D Iterations

In [36]:
x= np.arange(0,8).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
for i in x:
    print(i)

In [ ]:
for i in x :
    for j in i :
        print(j)

In [ ]:
for i in x:
    for j  in i :
        for k in j:
            print(k)

#### Nditer

In [37]:
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
for i in np.nditer(x):
    print(i)

#### Enumerate

In [ ]:
x= np.arange(0,12).reshape(3,4)
x

In [ ]:
for index, i in np.ndenumerate(x):
    print(index, i)

## Other Operations [Part -21]

In [ ]:
np.ravel(a)

In [ ]:
a.T #traverse

##### Type Casting

In [ ]:
a.astype(float)
a.astype(int)
a.astype(complex)

##### Flipud FliplrArrays

In [ ]:
np.fliplr(x)

In [ ]:
np.flipud(x)

In [ ]:
anp.fill_diagonal(np.fliplr(a), [1,2,3])

##### Create Copy

In [ ]:
r_copy=r.copy()
r_copy